run:
  deadline: 5m

linters:
  enable-all: true
  disable:
    - gosimple
    - gocyclo
    - gochecknoinits
    - golint
    - gochecknoglobals
    - dupl
    - interfacer
    - gosec
    - unparam
    - lll
    - maligned
    - nakedret
    - scopelint
    - prealloc
    - varcheck
    - goconst
